/**
 * These lists are Paul Nation's Vocabulary Size Test(Vocabulary size test (monolingual, 20,000, version A))
 * see: {@link https://www.wgtn.ac.nz/lals/resources/paul-nations-resources/vocabulary-tests}
 *
 * Nation, I. S. P. (2012). "The Vocabulary Size Test". {@link https://www.wgtn.ac.nz/lals/resources/paul-nations-resources/vocabulary-tests/the-vocabulary-size-test/Vocabulary-Size-Test-information-and-specifications.pdf}
 */

export const WORD_LIST_ = [
	"see",
	"time",
	"period",
	"figure",
	"poor",
	"microphone",
	"nil",
	"pub",
	"circle",
	"dig",
	"soldier",
	"restore",
	"pro",
	"compound",
	"deficit",
	"strap",
	"weep",
	"haunt",
	"cube",
	"butler",
	"nun",
	"olive",
	"shudder",
	"threshold",
	"demography",
	"malign",
	"strangle",
	"dinosaur",
	"jug",
	"crab",
	"quilt",
	"tummy",
	"eclipse",
	"excrete",
	"ubiquitous",
	"marrow",
	"cabaret",
	"cavalier",
	"veer",
	"yoghurt",
	"octopus",
	"monologue",
	"candid",
	"nozzle",
	"psychosis",
	"ruck",
	"rouble",
	"canonical",
	"puree",
	"vial",
	"counterclaim",
	"refectory",
	"trill",
	"talon",
	"plankton",
	"soliloquy",
	"puma",
	"augur",
	"emir",
	"didactic",
	"cranny",
	"lectern",
	"azalea",
	"marsupial",
	"bawdy",
	"crowbar",
	"spangled",
	"aver",
	"retro",
	"rascal",
	"tweezers",
	"bidet",
	"sloop",
	"swingeing",
	"cenotaph",
	"denouement",
	"bittern",
	"reconnoitre",
	"magnanimity",
	"effete",
	"rollick",
	"gobbet",
	"rigmarole",
	"alimony",
	"roughshod",
	"copra",
	"bier",
	"torpid",
	"dachshund",
	"cadenza",
	"obtrude",
	"panzer",
	"cyborg",
	"zygote",
	"sylvan",
	"sagacious",
	"spatiotemporal",
	"casuist",
	"cyberpunk",
	"pussyfoot",
] as const;

export const SECTION_WORD_SIZE = 10;

export const WORD_LIST_SECTIONS_ = WORD_LIST_.flatMap((v, i, arr) =>
	i % SECTION_WORD_SIZE ? [] : [arr.slice(i, i + SECTION_WORD_SIZE)],
);

export const TEST_LIST_ = {
	see: {
		sentence: "They <saw it>.",
		choices: [
			"closed it tightly",
			"waited for it",
			"looked at it",
			"started it up",
		],
	},
	time: {
		sentence: "They have a lot of <time>.",
		choices: ["money", "food", "hours", "friends"],
	},
	period: {
		sentence: "It was a difficult <period>.",
		choices: ["question", "time", "thing to do", "book"],
	},
	figure: {
		sentence: "Is this the right <figure>?",
		choices: ["answer", "place", "time", "number"],
	},
	poor: {
		sentence: "We <are poor>.",
		choices: [
			"have no money",
			"feel happy",
			"are very interested",
			"do not like to work hard",
		],
	},
	microphone: {
		sentence: "Please use the <microphone>.",
		choices: [
			"machine for making food hot",
			"machine that makes sounds louder",
			"machine that makes things look bigger",
			"small telephone that can be carried around",
		],
	},
	nil: {
		sentence: "His mark for that question was <nil>.",
		choices: ["very bad", "nothing", "very good", "in the middle"],
	},
	pub: {
		sentence: "They went to the <pub>.",
		choices: [
			"place where people drink and talk",
			"place that looks after money",
			"large building with many shops",
			"building for swimming",
		],
	},
	circle: {
		sentence: "Make a <circle>.",
		choices: [
			"rough picture",
			"space with nothing in it",
			"round shape",
			"large hole",
		],
	},
	dig: {
		sentence: "Our dog often <digs>.",
		choices: [
			"solves problems with things",
			"creates a hole in the ground",
			"wants to sleep",
			"enters the water",
		],
	},
	soldier: {
		sentence: "He is a <soldier>.",
		choices: [
			"person in a business",
			"person who studies",
			"person who uses metal",
			"person in the army",
		],
	},
	restore: {
		sentence: "It has been <restored>.",
		choices: [
			"said again",
			"given to a different person",
			"made like new again",
			"given a lower price",
		],
	},
	pro: {
		sentence: "He's <a pro>.",
		choices: [
			"someone who is employed to find out important secrets",
			"a stupid person",
			"someone who writes for a newspaper",
			"someone who is paid for playing sport",
		],
	},
	compound: {
		sentence: "They made a new <compound>.",
		choices: [
			"agreement",
			"thing made of two or more parts",
			"group of people forming a business",
			"guess based on past experience",
		],
	},
	deficit: {
		sentence: "The company <had a large deficit>.",
		choices: [
			"spent a lot more money than it earned",
			"went down a lot in value",
			"had a plan for its spending that used a lot of money",
			"had a lot of money stored in the bank",
		],
	},
	strap: {
		sentence: "He broke the <strap>.",
		choices: [
			"promise",
			"top cover",
			"shallow dish for food",
			"strip of strong material",
		],
	},
	weep: {
		sentence: "He <wept>.",
		choices: ["finished his course", "cried", "died", "worried"],
	},
	haunt: {
		sentence: "The house is <haunted>.",
		choices: ["full of decorations", "rented", "empty", "full of ghosts"],
	},
	cube: {
		sentence: "I need one more <cube>.",
		choices: [
			"sharp thing used for joining things",
			"solid square block",
			"tall cup with no saucer",
			"piece of stiff paper folded in half",
		],
	},
	butler: {
		sentence: "They have a <butler>.",
		choices: [
			"man servant",
			"machine for cutting up trees",
			"private teacher",
			"cool dark room under the house",
		],
	},
	nun: {
		sentence: "We saw a <nun>.",
		choices: [
			"long thin creature that lives in the earth",
			"terrible accident",
			"woman following a strict religious life",
			"unexplained bright light in the sky",
		],
	},
	olive: {
		sentence: "We bought <olives>.",
		choices: [
			"oily fruit",
			"scented flowers",
			"men's swimming clothes",
			"tools for digging",
		],
	},
	shudder: {
		sentence: "The boy <shuddered>.",
		choices: [
			"spoke with a low voice",
			"almost fell",
			"shook",
			"called out loudly",
		],
	},
	threshold: {
		sentence: "They raised the <threshold>.",
		choices: [
			"flag",
			"point or line where something changes",
			"roof inside a building",
			"cost of borrowing money",
		],
	},
	demography: {
		sentence: "This book is about <demography>.",
		choices: [
			"the study of patterns of land use",
			"the study of the use of pictures to show facts about numbers",
			"the study of the movement of water",
			"the study of population",
		],
	},
	malign: {
		sentence: "His <malign> influence is still felt.",
		choices: ["good", "evil", "very important", "secret"],
	},
	strangle: {
		sentence: "He <strangled her>.",
		choices: [
			"killed her by pressing her throat",
			"gave her all the things she wanted",
			"took her away by force",
			"admired her greatly",
		],
	},
	dinosaur: {
		sentence: "The children were pretending to be <dinosaurs>.",
		choices: [
			"robbers who work at sea",
			"very small creatures with human form but with wings",
			"large creatures with wings that breathe fire",
			"animals that lived an extremely long time ago",
		],
	},
	jug: {
		sentence: "He was holding <a jug>.",
		choices: [
			"a container for pouring liquids",
			"an informal discussion",
			"a soft cap",
			"a weapon that blows up",
		],
	},
	crab: {
		sentence: "Do you like <crabs>?",
		choices: [
			"very thin small cakes",
			"tight",
			"sea creatures that always walk to one side",
			"large black insects that sing at night",
		],
	},
	quilt: {
		sentence: "They made a <quilt>.",
		choices: [
			"statement about who should get their property when they die",
			"firm agreement",
			"thick warm cover for a bed",
			"feather pen",
		],
	},
	tummy: {
		sentence: "Look at my <tummy>.",
		choices: [
			"fabric to cover the head",
			"stomach",
			"small soft animal",
			"finger used for gripping",
		],
	},
	eclipse: {
		sentence: "<There was an eclipse>.",
		choices: [
			"A strong wind blew all day",
			"I heard something hit the water",
			"A large number of people were killed",
			"The sun was hidden by the moon",
		],
	},
	excrete: {
		sentence: "This was <excreted> recently.",
		choices: [
			"pushed or sent out",
			"made clear",
			"discovered by a science experiment",
			"put on a list of illegal things",
		],
	},
	ubiquitous: {
		sentence: "Many unwanted plants <are ubiquitous>.",
		choices: [
			"are difficult to get rid of",
			"have long",
			"are found everywhere",
			"die away in the winter",
		],
	},
	marrow: {
		sentence: "This is <the marrow>.",
		choices: [
			"symbol that brings good luck to a team",
			"soft centre of a bone",
			"control for guiding a plane",
			"increase in salary",
		],
	},
	cabaret: {
		sentence: "We saw the <cabaret>.",
		choices: [
			"painting covering a whole wall",
			"song and dance performance",
			"small crawling creature",
			"person who is half fish",
		],
	},
	cavalier: {
		sentence: "He treated her <in a cavalier manner>.",
		choices: [
			"without care",
			"with good manners",
			"awkwardly",
			"as a brother would",
		],
	},
	veer: {
		sentence: "The car <veered>.",
		choices: [
			"moved shakily",
			"changed course",
			"made a very loud noise",
			"slid without the wheels turning",
		],
	},
	yoghurt: {
		sentence: "This <yoghurt> is disgusting.",
		choices: [
			"dark grey mud found at the bottom of rivers",
			"unhealthy",
			"thick",
			"large purple fruit with soft flesh",
		],
	},
	octopus: {
		sentence: "They saw <an octopus>.",
		choices: [
			"a large bird that hunts at night",
			"a ship that can go under water",
			"a machine that flies by means of turning blades",
			"a sea creature with eight legs",
		],
	},
	monologue: {
		sentence: "Now he has a <monologue>.",
		choices: [
			"single piece of glass to hold over his eye to help him to see",
			"long turn at talking without being interrupted",
			"position with all the power",
			"picture made by joining letters together in interesting ways",
		],
	},
	candid: {
		sentence: "Please <be candid>.",
		choices: [
			"be careful",
			"show sympathy",
			"show fairness to both sides",
			"say what you really think",
		],
	},
	nozzle: {
		sentence: "Aim the <nozzle> toward it.",
		choices: [
			"space that light passes through in a camera",
			"dry patch of skin",
			"pipe attachment that forces water",
			"sharp part of a fork",
		],
	},
	psychosis: {
		sentence: "He has <a psychosis>.",
		choices: [
			"an inability to move",
			"an oddly coloured patch of skin",
			"a body organ that processes sugar",
			"a mental illness",
		],
	},
	ruck: {
		sentence: "He got hurt in the <ruck>.",
		choices: [
			"region between the stomach and the top of the leg",
			"noisy street fight",
			"group of players gathered round the ball in some ball games",
			"race across a field of snow",
		],
	},
	rouble: {
		sentence: "He had a lot of <roubles>.",
		choices: [
			"very valuable red stones",
			"distant members of his family",
			"Russian money",
			"moral or other difficulties in the mind",
		],
	},
	canonical: {
		sentence: "These are <canonical examples>.",
		choices: [
			"examples which break the usual rules",
			"examples taken from a religious book",
			"regular and widely accepted examples",
			"examples discovered very recently",
		],
	},
	puree: {
		sentence: "This <puree> is bright green.",
		choices: [
			"fruit or vegetables in liquid form",
			"dress worn by women in India",
			"skin of a fruit",
			"very thin material for evening dresses",
		],
	},
	vial: {
		sentence: "Put it in a <vial>.",
		choices: [
			"device which stores electricity",
			"country residence",
			"dramatic scene",
			"small glass bottle",
		],
	},
	counterclaim: {
		sentence: "They made <a counterclaim>.",
		choices: [
			"a demand response made by one side in a law case",
			"a request for a shop to take back things with faults",
			"an agreement between two companies to exchange work",
			"a decorative cover for a bed",
		],
	},
	refectory: {
		sentence: "We met in the <refectory>.",
		choices: [
			"room for eating",
			"office where legal papers can be signed",
			"room for several people to sleep in",
			"room with glass walls for growing plants",
		],
	},
	trill: {
		sentence: "He practised the <trill>.",
		choices: [
			"repeated high musical sound",
			"type of stringed instrument",
			"way of throwing the ball",
			"dance step of turning round very fast on the toes",
		],
	},
	talon: {
		sentence: "Just look at those <talons>",
		choices: [
			"high points of mountains",
			"sharp hooks on the feet of a hunting bird",
			"heavy metal coats to protect against weapons",
			"people who make fools of themselves without realizing it",
		],
	},
	plankton: {
		sentence: "We saw a lot of <plankton> here.",
		choices: [
			"poisonous plants that spread very quickly",
			"very small plants or animals found in water",
			"trees producing hard wood",
			"grey soil that often causes land to slip",
		],
	},
	soliloquy: {
		sentence: "That was an excellent <soliloquy>",
		choices: [
			"song for six people",
			"short clever saying with a deep meaning",
			"entertainment using lights and music",
			"speech in the theatre by a character who is alone",
		],
	},
	puma: {
		sentence: "They saw a <puma>.",
		choices: [
			"small house made of mud bricks",
			"tree from hot",
			"large wild cat",
			"very strong wind that lifts anything in its path",
		],
	},
	augur: {
		sentence: "It <augured well>.",
		choices: [
			"promised good things for the future",
			"agreed with what was expected",
			"had a colour that looked good with something else",
			"rang with a clear",
		],
	},
	emir: {
		sentence: "We saw the <emir>.",
		choices: [
			"bird with two long curved tail feathers",
			"woman who cares for other people's children in eastern countries",
			"Middle Eastern chief with power in his own land",
			"house made from blocks of ice",
		],
	},
	didactic: {
		sentence: "The story <is very didactic>.",
		choices: [
			"tries hard to teach something",
			"is very difficult to believe",
			"deals with exciting actions",
			"is written with unclear meaning",
		],
	},
	cranny: {
		sentence: "Look what we found in the <cranny>",
		choices: [
			"sale of unwanted objects",
			"narrow opening",
			"space for storing things under the roof of a house",
			"large wooden box",
		],
	},
	lectern: {
		sentence: "He stood at the <lectern>.",
		choices: [
			"desk made to hold a book at a good height for reading",
			"table or block used for church ceremonies",
			"place where you buy drinks",
			"very edge",
		],
	},
	azalea: {
		sentence: "This <azalea> is very pretty.",
		choices: [
			"small tree with many flowers growing in groups",
			"light natural fabric",
			"long piece of material worn in India",
			"sea shell shaped like a fan",
		],
	},
	marsupial: {
		sentence: "It is <a marsupial>.",
		choices: [
			"an animal with hard feet",
			"a plant that takes several years to grow",
			"a plant with flowers that turn to face the sun",
			"an animal with a pocket for babies",
		],
	},
	bawdy: {
		sentence: "It was very <bawdy>.",
		choices: ["unpredictable", "innocent", "rushed", "indecent"],
	},
	crowbar: {
		sentence: "He used a <crowbar>.",
		choices: [
			"heavy iron pole with a curved end",
			"false name",
			"sharp tool for making holes in leather",
			"light metal walking stick",
		],
	},
	spangled: {
		sentence: "Her dress was <spangled>.",
		choices: [
			"torn into thin strips",
			"covered with small bright decorations",
			"made with lots of folds of fabric",
			"ruined by touching something very hot",
		],
	},
	aver: {
		sentence: "She <averred> that it was the truth.",
		choices: ["refused to agree", "declared", "believed", "warned"],
	},
	retro: {
		sentence: "It had <a retro look>.",
		choices: [
			"a very fashionable look",
			"the look of a piece of modern art",
			"the look of something which has been used a lot before",
			"the look of something from an earlier time",
		],
	},
	rascal: {
		sentence: "She is such <a rascal> sometimes.",
		choices: [
			"an unbeliever",
			"a dedicated student",
			"a hard worker",
			"a bad girl",
		],
	},
	tweezers: {
		sentence: "They used <tweezers>.",
		choices: [
			"small pieces of metal for holding papers together",
			"small pieces of string for closing wounds",
			"a tool with two blades for picking up or holding small objects",
			"strong tool for cutting plants",
		],
	},
	bidet: {
		sentence: "They have a <bidet>.",
		choices: [
			"low basin for washing the body after using the toilet",
			"large fierce brown dog",
			"small private swimming pool",
			"man to help in the house",
		],
	},
	sloop: {
		sentence: "Whose <sloop> is that?",
		choices: [
			"warm hat",
			"light sailing boat",
			"left over food",
			"untidy work",
		],
	},
	swingeing: {
		sentence: "They got <swingeing fines>.",
		choices: [
			"very large fines",
			"very small fines",
			"fines paid in small amounts at a time",
			"fines that vary depending on income",
		],
	},
	cenotaph: {
		sentence: "We met at the <cenotaph>.",
		choices: [
			"large and important church",
			"public square in the centre of a town",
			"memorial for people buried somewhere else",
			"underground train station",
		],
	},
	denouement: {
		sentence: "I was disappointed with the <denouement>.",
		choices: [
			"ending of a story which solves the mystery",
			"amount of money paid for a piece of work",
			"small place to live which is part of a bigger building",
			"official report of the results of a political meeting",
		],
	},
	bittern: {
		sentence: "She saw a <bittern>.",
		choices: [
			"large bottle for storing liquid",
			"small green grass snake",
			"false picture caused by hot air",
			"water bird with long legs and a very loud call",
		],
	},
	reconnoitre: {
		sentence: "They have gone to <reconnoitre>.",
		choices: [
			"think again",
			"make an examination of a new place",
			"have a good time to mark a happy event",
			"complain formally",
		],
	},
	magnanimity: {
		sentence: "We will never forget her <magnanimity>.",
		choices: [
			"very offensive and unfriendly manners",
			"courage in times of trouble",
			"generosity",
			"completely sincere words",
		],
	},
	effete: {
		sentence: "He has become <effete>.",
		choices: [
			"weak and soft",
			"too fond of strong drink",
			"unable to leave his bed",
			"extremely easy to annoy",
		],
	},
	rollick: {
		sentence: "They were <rollicking>.",
		choices: [
			"driving very fast",
			"staying away from school without being permitted to",
			"having fun in a noisy and spirited way",
			"sliding on snow using round boards",
		],
	},
	gobbet: {
		sentence: "The cat left a <gobbet> behind.",
		choices: [
			"strip of torn material",
			"footprint",
			"piece of solid waste from the body",
			"lump of food returned from the stomach",
		],
	},
	rigmarole: {
		sentence: "I hate the <rigmarole>.",
		choices: [
			"very fast and difficult dance for eight people",
			"funny character in the theatre",
			"form which must be completed each year for tax purposes",
			"long",
		],
	},
	alimony: {
		sentence: "The article was about <alimony>.",
		choices: [
			"feelings of bitterness and annoyance",
			"money for the care of children",
			"giving praise for excellent ideas",
			"a metal which breaks easily and is bluish white",
		],
	},
	roughshod: {
		sentence: "He <rode roughshod>.",
		choices: [
			"travelled without good preparation",
			"made lots of mistakes",
			"did not consider other people's feelings",
			"did not care about his own comfort",
		],
	},
	copra: {
		sentence: "They supply <copra>.",
		choices: [
			"a highly poisonous substance used to kill unwanted plants",
			"the dried meat from a large nut used to make oil",
			"an illegal substance which makes people feel good for a short time",
			"strong rope used on sailing ships",
		],
	},
	bier: {
		sentence: "She lay on the <bier>.",
		choices: [
			"folding garden chair",
			"grass next to a river",
			"place where boats can be tied up",
			"board on which a dead body is carried",
		],
	},
	torpid: {
		sentence: "He was <in a torpid state>.",
		choices: [
			"undecided",
			"filled with very strong feelings",
			"confused and anxious",
			"slow and sleepy",
		],
	},
	dachshund: {
		sentence: "She loves her <dachshund>.",
		choices: [
			"warm fur hat",
			"thick floor rug with special patterns",
			"small dog with short legs and a long back",
			"old musical instrument with twelve strings",
		],
	},
	cadenza: {
		sentence: "What did you think of the <cadenza>?",
		choices: [
			"cake topped with cream and fruit",
			"large box hanging from a wire that carries people up a mountain",
			"slow formal dance from Italy",
			"passage in a piece of music that shows the player's great skill",
		],
	},
	obtrude: {
		sentence: "These thoughts <obtruded themselves>.",
		choices: [
			"got themselves lost or forgotten",
			"did not agree with each other",
			"got mixed up with each other",
			"pushed themselves forward in the mind",
		],
	},
	panzer: {
		sentence: "They saw the <panzers> getting nearer.",
		choices: [
			"players in a marching band",
			"fighter planes",
			"large",
			"policewomen",
		],
	},
	cyborg: {
		sentence: "She read about <a cyborg>.",
		choices: [
			"an integrated human",
			"a musical instrument with forty strings",
			"a small",
			"a warm wind in winter",
		],
	},
	zygote: {
		sentence: "It is <a zygote>.",
		choices: [
			"an early phase of sexual reproduction",
			"a lot of bother over nothing",
			"a small animal found in southern Africa",
			"a gun used to launch rockets",
		],
	},
	sylvan: {
		sentence: "The painting had a <sylvan> theme.",
		choices: ["lost love", "wandering", "forest", "casual folk"],
	},
	sagacious: {
		sentence: "She had many ideas that were <sagacious>.",
		choices: [
			"instinctively clever",
			"ridiculous and wild",
			"about abusing people and being abused",
			"rebellious and dividing",
		],
	},
	spatiotemporal: {
		sentence: "My theory is <spatiotemporal>.",
		choices: [
			"focussed on small details",
			"annoying to people",
			"objectionably modern",
			"oriented to time and space",
		],
	},
	casuist: {
		sentence: "Don't <play the casuist> with me",
		choices: [
			"focus only on self",
			"act like a tough guy",
			"make judgments about my conduct of duty",
			"be stupid",
		],
	},
	cyberpunk: {
		sentence: "I like <cyberpunk>.",
		choices: [
			"medicine that does not use drugs",
			"one variety of science fiction",
			"the art and science of eating",
			"a society ruled by technical experts",
		],
	},
	pussyfoot: {
		sentence: "Let's not <pussyfoot around>.",
		choices: [
			"criticise unreasonably",
			"take care to avoid confrontation",
			"attack indirectly",
			"suddenly start",
		],
	},
} as const;

export const TEST_ANSWERS = {
	see: 2,
	time: 2,
	period: 1,
	figure: 3,
	poor: 0,
	microphone: 1,
	nil: 1,
	pub: 0,
	circle: 2,
	dig: 1,
	soldier: 3,
	restore: 2,
	pro: 3,
	compound: 1,
	deficit: 0,
	strap: 3,
	weep: 1,
	haunt: 3,
	cube: 1,
	butler: 0,
	nun: 2,
	olive: 0,
	shudder: 2,
	threshold: 1,
	demography: 3,
	malign: 1,
	strangle: 0,
	dinosaur: 3,
	jug: 0,
	crab: 2,
	quilt: 2,
	tummy: 1,
	eclipse: 3,
	excrete: 0,
	ubiquitous: 2,
	marrow: 1,
	cabaret: 1,
	cavalier: 0,
	veer: 1,
	yoghurt: 2,
	octopus: 3,
	monologue: 1,
	candid: 3,
	nozzle: 2,
	psychosis: 3,
	ruck: 2,
	rouble: 2,
	canonical: 2,
	puree: 0,
	vial: 3,
	counterclaim: 0,
	refectory: 0,
	trill: 0,
	talon: 1,
	plankton: 1,
	soliloquy: 3,
	puma: 2,
	augur: 0,
	emir: 2,
	didactic: 0,
	cranny: 1,
	lectern: 0,
	azalea: 0,
	marsupial: 3,
	bawdy: 3,
	crowbar: 0,
	spangled: 1,
	aver: 1,
	retro: 3,
	rascal: 3,
	tweezers: 2,
	bidet: 0,
	sloop: 1,
	swingeing: 0,
	cenotaph: 2,
	denouement: 0,
	bittern: 3,
	reconnoitre: 1,
	magnanimity: 2,
	effete: 0,
	rollick: 2,
	gobbet: 3,
	rigmarole: 3,
	alimony: 1,
	roughshod: 2,
	copra: 1,
	bier: 3,
	torpid: 3,
	dachshund: 2,
	cadenza: 3,
	obtrude: 3,
	panzer: 2,
	cyborg: 0,
	zygote: 0,
	sylvan: 2,
	sagacious: 0,
	spatiotemporal: 3,
	casuist: 2,
	cyberpunk: 1,
	pussyfoot: 1,
} as const;
